fix: sandbox for Dockerfile

diff --git a/core/load b/core/load
--- a/core/load
+++ b/core/load
@@ -11,7 +11,6 @@ sandbox::load() {
   export PLUGIN_NAME=$PLUGIN_NAME
   export PLUGIN_VERSION=$PLUGIN_VERSION
   export PLUGIN_DESCRIPTION=$PLUGIN_DESCRIPTION
-  
 
   local sandbox_dir="$PLUGIN_SANDBOX_SANDBOXS_DIR/$typ"
   local sandbox_config=$sandbox_dir/config
@@ -38,16 +37,20 @@ sandbox::load() {
   export PLUGIN_SANDBOX_COMMAND=${command:-$PLUGIN_SANDBOX_COMMAND}
   export PLUGIN_SANDBOX_RUNNER_ID=$(os::uuid)
   export PLUGIN_SANDBOX_RUNNER_CONTAINER="sandbox_${typ}_${PLUGIN_SANDBOX_RUNNER_ID}"
-  export PLUGIN_SANDBOX_RUNNER_PORT=${PLUGIN_SANDBOX_RUNNER_PORT:-$PORT}
 
-  if [ -z "$PLUGIN_SANDBOX_RUNNER_PORT" ]; then
-    PLUGIN_SANDBOX_RUNNER_PORT="8024"
-  fi
+  if [ "$typ" != "." ]; then
+    # check image is exist
+    if [ "$(sandbox::is_image_exists $PLUGIN_SANDBOX_IMAGE_NAME $PLUGIN_SANDBOX_IMAGE_VERSION)" = "false" ]; then
+      log::error "[sandbox::load] sandbox (${PLUGIN_SANDBOX_NAME}) image ($PLUGIN_SANDBOX_IMAGE) not found"
+      exit 1
+    fi
+  else
+    if [ ! -f "$PLUGIN_SANDBOX_CONTEXT/$PLUGIN_SANDBOX_DOCKERFILE_NAME" ]; then
+      log::info "[$(timestamp)] local Dockerfile not found ..."
+      return 1
+    fi
 
-  # check image is exist
-  if [ "$(sandbox::is_image_exists $PLUGIN_SANDBOX_IMAGE_NAME $PLUGIN_SANDBOX_IMAGE_VERSION)" = "false" ]; then
-    log::error "[sandbox::load] sandbox (${PLUGIN_SANDBOX_NAME}) image ($PLUGIN_SANDBOX_IMAGE) not found"
-    exit 1
+    log::info "[$(timestamp)] run with local Dockerfile ..."
   fi
 }
 
diff --git a/core/run b/core/run
--- a/core/run
+++ b/core/run
@@ -30,26 +30,35 @@ sandbox::run() {
   fi
 
   sandbox::load "$typ" "$version" "$command"
+
   # sandbox::prepare "$typ"
 
   cd $PLUGIN_SANDBOX_COMPOSE_DIR
-  if [ -n "$DEBUG" ]; then
-    $DOCKER_COMPOSE config
-  fi
 
   # log::debug "run => $DOCKER_COMPOSE run app \"$command\""
   # $DOCKER_COMPOSE run app "$command"
 
   local tmp_error=$(os::tmp_file)
-  if [ -f "$PLUGIN_SANDBOX_COMPOSE_DIR/$PLUGIN_SANDBOX_DOCKERFILE_NAME" ]; then
+  if [ -f "$PLUGIN_SANDBOX_CONTEXT/$PLUGIN_SANDBOX_DOCKERFILE_NAME" ]; then
     export PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME=$PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME_FOR_DOCKERFILE
-
-    # need build
-    $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME up -d >>/dev/null 2>$tmp_error
-  else
-    $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME up -d >>/dev/null 2>$tmp_error
   fi
 
+  if [ -n "$DEBUG" ]; then
+    $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME config
+  fi
+
+  if [ "$PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME" != "" ]; then
+    # need build
+    log::info "[$(timestamp)] building fresh ..."
+    $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME build >>/dev/null 2>$tmp_error
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)] failed to build sandbox: $PLUGIN_SANDBOX_RUNNER_CONTAINER"
+      cat $tmp_error
+      return 1
+    fi
+  fi
+
+  $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME up -d >>/dev/null 2>$tmp_error
   if [ "$?" != "0" ]; then
     log::error "[$(timestamp)] failed to start sandbox: $PLUGIN_SANDBOX_RUNNER_CONTAINER"
     cat $tmp_error
